/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseDatepicker: (typeof import('../components/table/base-datepicker.vue'))['default']
    BasePagination: (typeof import('../components/table/base-pagination.vue'))['default']
    BillSaveForm: (typeof import('../views/bill/bill-save-form.vue'))['default']
    DateColumn: (typeof import('../components/table/date-column.vue'))['default']
    ElAside: (typeof import('element-plus/es'))['ElAside']
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar']
    ElButton: (typeof import('element-plus/es'))['ElButton']
    ElCard: (typeof import('element-plus/es'))['ElCard']
    ElCol: (typeof import('element-plus/es'))['ElCol']
    ElContainer: (typeof import('element-plus/es'))['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDialog: (typeof import('element-plus/es'))['ElDialog']
    ElDivider: (typeof import('element-plus/es'))['ElDivider']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: (typeof import('element-plus/es'))['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElImage: (typeof import('element-plus/es'))['ElImage']
    ElInput: (typeof import('element-plus/es'))['ElInput']
    ElLink: (typeof import('element-plus/es'))['ElLink']
    ElMain: (typeof import('element-plus/es'))['ElMain']
    ElMenu: (typeof import('element-plus/es'))['ElMenu']
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem']
    ElMenuItemGroup: (typeof import('element-plus/es'))['ElMenuItemGroup']
    ElPagination: (typeof import('element-plus/es'))['ElPagination']
    ElPopover: (typeof import('element-plus/es'))['ElPopover']
    ElRow: (typeof import('element-plus/es'))['ElRow']
    ElSpace: (typeof import('element-plus/es'))['ElSpace']
    ElSubMenu: (typeof import('element-plus/es'))['ElSubMenu']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTable: (typeof import('element-plus/es'))['ElTable']
    ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn']
    ElText: (typeof import('element-plus/es'))['ElText']
    ReturnStatus: (typeof import('../components/cards/return-status-card.vue'))['default']
    ReturnStatusCard: (typeof import('../components/cards/return-status-card.vue'))['default']
    RouterLink: (typeof import('vue-router'))['RouterLink']
    RouterView: (typeof import('vue-router'))['RouterView']
    SideBar: (typeof import('../components/side-bar/side-bar.vue'))['default']
    SideBarItem: (typeof import('../components/side-bar/side-bar-item.vue'))['default']
    SvgImg: (typeof import('../components/svg-img.vue'))['default']
    TopBar: (typeof import('../components/top-bar.vue'))['default']
  }
  export interface ComponentCustomProperties {
    vLoading: (typeof import('element-plus/es'))['ElLoadingDirective']
  }
}
